name: Filters Microservice Deployment

on:
  push:
    paths:
      - 'filters/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd filters

          # Login to DockerHub:
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          FILTERS_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/filters:0.0.${{ github.run_number }}
          docker build -t $FILTERS_IMAGE_NAME .
          docker push $FILTERS_IMAGE_NAME

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    strategy:
      matrix:
        region: ['eu-west-1']
        # Add your desired regions here

    env:
      AWS_DEFAULT_REGION: ${{ matrix.region }}
      AWS_REGION: ${{ matrix.region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      ALB_URL: ${{ secrets.ALB_URL }}
      DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}
      FILTERS_QUEUE_URL: ${{ secrets.FILTERS_QUEUE_URL }}
      YOLO_QUEUE_URL: ${{ secrets.YOLO_QUEUE_URL }}
      EC2_INSTANCE_IDS: ${{ secrets.EC2_INSTANCE_IDS }}
      EC2_FILTERS_IP_ADDRESSES: ${{ secrets.EC2_FILTERS_IP_ADDRESSES }}
      NEW_RUNNING_INSTANCE_IPS: ${{ secrets.NEW_RUNNING_INSTANCE_IPS }}
      KEY: ${{ secrets.TF_PROJECT_PRIVATE_KEY }}

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      - name: Fetch EC2 Instance IP Addresses
        id: fetch-ec2-instances
        run: |
          EC2_INSTANCE_DETAILS=$(aws ec2 describe-instances --region ${{ matrix.region }} --filters "Name=tag:Name,Values=*filters*" "Name=tag:Name,Values=*yaelwil*" "Name=tag:Name,Values=*tf-project*" --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' --output json)
          echo "$EC2_INSTANCE_DETAILS" > instance_details.json
      
          EC2_FILTERS_IP_ADDRESSES=$(echo "$EC2_INSTANCE_DETAILS" | jq -r '.[][] | select(.[1] == "running") | .[2]' | tr '\n' ' ')
          echo "EC2_FILTERS_IP_ADDRESSES=$EC2_FILTERS_IP_ADDRESSES" >> $GITHUB_ENV

      - name: Fetch BUCKET_NAME
        run: |
          BUCKET_NAME=$(aws s3api list-buckets --query "Buckets[?contains(Name, 'yaelwil') && contains(Name, 'tf-project') && contains(Name, 'bucket')].Name | [0]" --output text)
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV


      - name: Fetch ALB_URL
        run: |
          ALB_URL=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, 'yaelwil') && contains(LoadBalancerName, 'tf-project') && contains(LoadBalancerName, 'alb')].DNSName | [0]" --output text)
          echo "ALB_URL=$ALB_URL" >> $GITHUB_ENV

      - name: Fetch DYNAMODB_TABLE_NAME
        run: |
          DYNAMODB_TABLE_NAME=$(aws dynamodb list-tables --query "TableNames[?contains(@, 'yaelwil') && contains(@, 'tf-project')]" --output text)
          echo "DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE_NAME" >> $GITHUB_ENV



      - name: Fetch FILTERS_QUEUE_URL
        run: |
          FILTERS_QUEUE_URL=$(aws sqs list-queues --query "QueueUrls[?contains(@, 'yaelwil') && contains(@, 'tf-project') && contains(@, 'filters')]" --output text)
          echo "FILTERS_QUEUE_URL=$FILTERS_QUEUE_URL" >> $GITHUB_ENV


      - name: Fetch YOLO_QUEUE_URL
        run: |
          YOLO_QUEUE_URL=$(aws sqs list-queues --query "QueueUrls[?contains(@, 'yaelwil') && contains(@, 'tf-project') && contains(@, 'yolov5')]" --output text)
          echo "YOLO_QUEUE_URL=$YOLO_QUEUE_URL" >> $GITHUB_ENV

      - name: Generate .env file
        run: |
          echo "BUCKET_NAME=${{ env.BUCKET_NAME }}" > .env
          echo "ALB_URL=${{ env.ALB_URL }}" >> .env
          echo "REGION=${{ matrix.region }}" >> .env
          echo "DYNAMODB_TABLE_NAME=${{ env.DYNAMODB_TABLE_NAME }}" >> .env
          echo "YOLO_QUEUE_NAME=${{ env.YOLO_QUEUE_URL/https:\/\//http:\/\/ }}:80" >> .env
          echo "FILTERS_QUEUE_NAME=${{ env.FILTERS_QUEUE_URL/https:\/\//http:\/\/ }}:80" >> .env

          cat .env