name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'filters/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd filters
          
          # Login to DockerHub:         
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          FILTERS_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/filters:${{ github.run_number }}
          docker build -t $FILTERS_IMAGE_NAME .
          docker push $FILTERS_IMAGE_NAME       

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          # TODO your implementation here....     
     
